### ISSUE TITLE
Clicking on black Inner causes exception

### ISSUE THREAD

**Issue by cjmayo** [edyoung/gnofract4d#26]
When paint mode is active with the default Mandelbrot:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/fract4dgui/gtkfractal.py", line 956, in onButtonRelease
    if self.filterPaintModeRelease(event):
  File "/usr/lib64/python3.6/site-packages/fract4dgui/gtkfractal.py", line 946, in filterPaintModeRelease
    self.onPaint(self.newx, self.newy)
  File "/usr/lib64/python3.6/site-packages/fract4dgui/gtkfractal.py", line 930, in onPaint
    self.f.solids[color] = (int(r*255.0),int(g*255.0),int(b*255.0),255)
IndexError: list assignment index out of range
```

**Comment by edyoung** [comment]
fixed
