### ISSUE TITLE
Tests not working?

### ISSUE THREAD

**Issue by edyoung** [edyoung/gnofract4d#70]
@mindhells I'm trying to execute the tests while looking at the 'refactor part 2' and having some trouble getting them to run at all.  

Running on ubuntu 18.04. If I run 'pytest3 fract4d/tests' I get lots of errors like

```
=========================  test_gradient.py  =========================
unhandled exception occurred while testing test_gradient
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/logilab/common/pytest.py", line 447, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python3/dist-packages/logilab/common/pytest.py", line 763, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python3.5/unittest/main.py", line 63, in __init__
    self.module = __import__(module)
  File "/home/edwin/projects/gnofract4d/fract4d/tests/test_gradient.py", line 8, in <module>
    from . import testbase
SystemError: Parent module '' not loaded, cannot perform relative import
```

Any ideas why, or what I actually need to do to run these?

**Comment by edyoung** [comment]
Looks like I need to:

apt-get install pip3
pip3 install pytest

Then 'pytest' works with python3 and successfully runs tests.

The tests in the root dir/test.py are not being run

**Comment by edyoung** [comment]
Have them working now.
